project:
  type: website

website:
  title: "Mi sitio de reportes"
  navbar:
    left:
      - text: "Sobre este sitio"
        href: index.qmd
  sidebar:
    style: docked
    contents:
      - index.qmd
      - section: "Primer reporte"
        contents:
          - mis_reportes/reporte-01.qmd
      - section: "Segundo reporte"
        contents:
          - mis_reportes/reporte-02.qmd
      - section: "Último reporte"
        contents:
          - mis_reportes/reporte-03.qmd

format:
  html:
    theme: minty
    toc: true
    lang: es
